package application;

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=yourDatabaseName
spring.datasource.username=yourUsername
spring.datasource.password=yourPassword
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver